# Generated by Django 4.2.3 on 2023-07-12 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_offer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                ("image_url", models.CharField(max_length=2083)),
                ("project_url", models.CharField(max_length=2083)),
            ],
        ),
        migrations.DeleteModel(
            name="Offer",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
