# Generated by Django 4.2.3 on 2023-07-15 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_project_delete_offer_delete_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="skills",
            field=models.CharField(default="n/a", max_length=500),
        ),
    ]
